#! /bin/sh

# BSPWM configuration
# @arvmtt

# > autostart 
sxhkd &
picom &
nitrogen --restore &
polybar main &

# > configuration

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# > colors
bspc config normal_border_color   false 
bspc config focused_border_color  "#724d7c"
bspc config urgent_border_color   "#d1d1d6"
bspc config presel_feedback_color false

# - hides the focused border when there only is one window active.
for p in {single,borderless}_monocle; do bspc config "$p" true; done
